main:
  pattern: /{page}/{days}
  defaults: { _controller: NtechBoardBundle:Main:index, page: 1, days: 1 }
  requirements:
    days: 1|7|31
    page: \d+

main_with_params:
    pattern:  /page-{page}/days-{days}
    defaults: { _controller: NtechBoardBundle:Main:index }
    requirements:
      days: 1|7|31
      page: \d+

change_followed_by_me_status:
    pattern: /change-follow-status-{userId}
    defaults: { _controller: NtechBoardBundle:User:changeFollowedByMeStatus, _format: json }
    requirements:
      userId: \d+

check_if_message_already_reposted:
    pattern: /check_if_message_already_reposted-{originalMessageId}
    defaults: { _controller: NtechBoardBundle:Message:checkIfMessageAlreadyReposted, _format: json }
    requirements:
      originalMessageId: \d+

repost_message:
    pattern: /repost_message-{originalMessageId}-{redirectToRouteAfterRepost}
    defaults: { _controller: NtechBoardBundle:Message:repostMessage, _format: json }
    requirements:
      originalMessageId: \d+

load_replies:
    pattern: /load_replies-{messageId}
    defaults: { _controller: NtechBoardBundle:Message:loadReplies, _format: json }
    requirements:
      messageId: \d+

reply_to_message:
    pattern: /reply_to_message-{originalMessageId}
    defaults: { _controller: NtechBoardBundle:Message:replyToMessage, _format: json }
    requirements:
      originalMessageId: \d+

add_new_message:
    pattern: /add_new_message
    defaults: { _controller: NtechBoardBundle:Message:addNewMessage, _format: json }

login:
    pattern: /login
    defaults: { _controller: NtechBoardBundle:Authorization:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

register:
    pattern: /register
    defaults: { _controller: NtechBoardBundle:Authorization:register }

myboard:
    pattern: /myboard/{page}/{days}
    defaults: { _controller: NtechBoardBundle:Board:showMyBoard, page: 1, days: 1 }
    requirements:
      days: 1|7|31
      page: \d+

myboard_with_params:
    pattern: /myboard/page-{page}/days-{days}
    defaults: { _controller: NtechBoardBundle:Board:showMyBoard, page: 1, days: 1 }
    requirements:
      days: 1|7|31
      page: \d+

search_user:
    pattern: /search_user
    defaults: { _controller: NtechBoardBundle:Main:searchUser }
    methods: [GET]

my_followers:
    pattern: /my_followers
    defaults: { _controller: NtechBoardBundle:Board:showMyFollowers }

view_profile:
    pattern: /users/{username}/page-{page}
    defaults: { _controller: NtechBoardBundle:User:showProfile, page: 1 }