main:
  pattern: /{page}/{days}
  defaults: { _controller: NtechBoardBundle:Main:index, page: 1, days: 1 }
  requirements:
    days: 1|7|31
    page: \d+

main_with_params:
    pattern:  /page-{page}/days-{days}
    defaults: { _controller: NtechBoardBundle:Main:index }
    requirements:
      days: 1|7|31
      page: \d+

login:
    pattern: /login
    defaults: { _controller: NtechBoardBundle:Authorization:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

register:
    pattern: /register
    defaults: { _controller: NtechBoardBundle:Authorization:register }

myboard:
    pattern: /myboard
    defaults: { _controller: NtechBoardBundle:Board:showMyBoard }

search_user:
    pattern: /search_user
    defaults: { _controller: NtechBoardBundle:Main:searchUser }
    methods: [GET]

my_followers:
    pattern: /my_followers
    defaults: { _controller: NtechBoardBundle:Board:showMyFollowers }