main:
  pattern: /{page}/{days}
  defaults: { _controller: NtechBoardBundle:Main:index, page: 1, days: 1 }
  requirements:
    days: 1|7|31
    page: \d+

main_with_params:
    pattern:  /page-{page}/days-{days}
    defaults: { _controller: NtechBoardBundle:Main:index }
    requirements:
      days: 1|7|31
      page: \d+

change_followed_by_me_status:
    pattern: /change-follow-status-{userId}
    defaults: { _controller: NtechBoardBundle:User:changeFollowedByMeStatus, _format: json }
    requirements:
      userId: \d+

check_if_message_already_reposted:
    pattern: /check_if_message_already_reposted-{originalMessageId}
    defaults: { _controller: NtechBoardBundle:Message:checkIfMessageAlreadyReposted, _format: json }
    requirements:
      originalMessageId: \d+

repost_message:
    pattern: /repost_message-{originalMessageId}
    defaults: { _controller: NtechBoardBundle:Message:repostMessage, _format: json }
    requirements:
      originalMessageId: \d+

login:
    pattern: /login
    defaults: { _controller: NtechBoardBundle:Authorization:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

register:
    pattern: /register
    defaults: { _controller: NtechBoardBundle:Authorization:register }

myboard:
    pattern: /myboard
    defaults: { _controller: NtechBoardBundle:Board:showMyBoard }

search_user:
    pattern: /search_user
    defaults: { _controller: NtechBoardBundle:Main:searchUser }
    methods: [GET]

my_followers:
    pattern: /my_followers
    defaults: { _controller: NtechBoardBundle:Board:showMyFollowers }