<?php

namespace Ntech\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function getAllMessagesAndRepostsPerLastDay($limit = 50)
	{
		$query = $this->getEntityManager()->createQuery(
			'SELECT m, u FROM NtechBoardBundle:Message m JOIN m.user u WHERE m.addedAt > :date
			AND m.replyToMessage is NULL ORDER BY m.addedAt DESC'
		)->setParameter('date', date('Y-m-d H:i:s', time() - (60 * 60 * 24)))
		->setMaxResults($limit);

		return $query->getResult();
	}

	public function getAllMessagesByUserIds($userIds = array())
	{
		if(!is_array($userIds) || empty($userIds))
			throw new \Exception("Wrong \$userIds passed to getAllMessagesByUserIds");

		for($i = 0; $i < count($userIds); $i++)
			$userIds[$i] = (int)$userIds[$i];

		$userIdsString = implode(", ", $userIds);

		$query = $this->getEntityManager()->createQuery(
			"SELECT m FROM NtechBoardBundle:Message m JOIN m.user u
			 WHERE u.id IN ($userIdsString) ORDER BY m.addedAt DESC"
		);

		return $query->getResult();
	}
}
